config/routes.rb
Erhuamao::Application.routes.draw do
  
  get "travel_pages/index"

  resources :customizebookings

  resources :photocontests

  resources :gbookingdays

  resources :dianpins

  resources :questions

  resources :galleries

  resources :gbookings

  resources :bookings

  resources :brochure_destinations

  resources :brochure_interests

  resources :brochure_travels

  resources :brochures

  resources :pages

  resources :presses

  resources :events

  resources :photos

  resources :cities

  resources :travels do 
    resources :itineraries
    resources :datesprices
  end

  resources :destinations do
    resources :travels
  end

  resources :interests do
    resources :travels
  end

  resources :specialoffers

  resources :itineraries
  resources :datesprices

  devise_for :users
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session#, :via => Devise.mappings[:user].sign_out_via
    get 'signup' => 'devise/registrations#new', :as => :new_user_registration
    post 'signup' => 'devise/registrations#create', :as => :user_registration
    put 'signup' => 'devise/registrations#update'
    get "setting", :to => "users#setting"
    put "update_setting", :to => "users#update_setting"
    put "update_password", :to => "users#update_password"
    put "update_avatar", :to => "users#update_avatar"
    get "/users/:id", :to => "users#show", :as => :user
    get "/users/:id/dianpins", :to => "users#dianpins"
    get "/users/:id/bookings", :to => "users#bookings"
    get "/users/:id/questions", :to => "users#questions"
  end

  namespace :admin do
    resources :users do
      member do
        get :lock, :unlock, :generate_new_password_email
      end
    end
    resources :travels do 
      member do
        get :new_destination_travel
        post :create_destination_travel
        get :new_interest_travel
        post :create_interest_travel
        get :new_specialoffer_travel
        post :create_specialoffer_travel
        get :new_brochure_travel
        post :create_brochure_travel
      end
      resources :itineraries
      resources :datesprices
      resources :travel_pages do
        collection do
          put :assign
        end

        member do
          delete :detach
        end
      end
    end
    resources :datesprices
    resources :itineraries
    resources :destinations do
      resources :galleries
      member do
        get :new_brochure_destination
        post :create_brochure_destination
      end
    end
    resources :interests do
      member do
        get :new_brochure_interest
        post :create_brochure_interest
      end
    end
    resources :hotels do
      resources :galleries
    end
    resources :photos
    resources :specialoffers
    resources :presses
    resources :events
    resources :pages
    resources :banners
    resources :brochures
    resources :galleries do 
      resources :photos
    end
    resources :bookings
    resources :gbookings
    resources :questions
    resources :cities
    resources :photocontests
    resources :dianpins
    resources :shouyes
  end

  match "weibo_login" => "welcome#weibo_login"
  match "weibo_callback" => "welcome#weibo_callback"

  match "admin/travels/:id/destroy_destination_travel/:destination_id" => "admin/travels#destroy_destination_travel"
  match "admin/travels/:id/destroy_interest_travel/:interest_id" => "admin/travels#destroy_interest_travel"
  match "admin/travels/:id/destroy_specialoffer_travel/:specialoffer_id" => "admin/travels#destroy_specialoffer_travel"
  match "admin/travels/:id/destroy_brochure_travel/:brochure_id" => "admin/travels#destroy_brochure_travel"
  match "admin/interests/:id/destroy_brochure_interest/:brochure_id" => "admin/interests#destroy_brochure_interest"
  match "admin/destinations/:id/destroy_brochure_destination/:brochure_id" => "admin/destinations#destroy_brochure_destination"
  get 'admin' => 'admin/base#index'
  get 'admin/handle' => 'admin/base#handle'
  get 'search' => 'welcome#search'
  get 'travel_count' => 'welcome#travel_count'

  root :to => "welcome#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/gallery.rb
# -*- encoding : utf-8 -*-
class Gallery < ActiveRecord::Base
	has_many :photos

	has_many :hotels
	has_many :destinations
	has_many :cities
	has_many :travels
end

app/controllers/admin/galleries_controller.rb
# -*- encoding : utf-8 -*-
# insub's admin scaffold template
# rails g scaffold_controller_admin galleries title:string travel_id:integer resource:string resource_id:integer 

class Admin::GalleriesController < Admin::BaseController
  layout "admin"
  before_filter :authenticate_user!
  before_filter :require_admin  #, :only=> [:index], :except=> [:index]
  
  # GET /galleries
  # GET /galleries.xml
  def index
    @galleries = Gallery.order("updated_at DESC").page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.xml
  def show
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.xml
  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

  # POST /galleries
  # POST /galleries.xml
  def create
    @gallery = Gallery.new(params[:gallery])

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to(admin_galleries_url, :notice => 'Gallery was successfully created.') }
        format.xml  { render :xml => @gallery, :status => :created, :location => @gallery }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @gallery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.xml
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to([:admin, @gallery], :notice => 'Gallery was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @gallery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.xml
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to(admin_galleries_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/galleries_controller.rb
# -*- encoding : utf-8 -*-
class GalleriesController < ApplicationController

  # GET /galleries/1
  # GET /galleries/1.xml
  def show
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @gallery }
    end
  end

end

app/helpers/galleries_helper.rb
# -*- encoding : utf-8 -*-
module GalleriesHelper
end

app/views/admin/galleries/_form.html.erb
<%= form_for([:admin, @gallery],:html => {:class => "form-horizontal" }) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label">title</label>
    <div class="controls">
    <%= f.text_field :title %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/admin/galleries/edit.html.erb
<div class="row">
<h3>后台管理 > 编辑gallery <div class="pull-right"><%= link_to '查看', [:admin, @gallery] %> |
<%= link_to '返回列表', admin_galleries_path %></div></h3>
<hr>

<%= render 'form' %>

</div>

app/views/admin/galleries/index.html.erb
<div class="row">
<h3>后台管理 > Gallery列表 <div class="pull-right"><%= link_to '创建新Gallerys', new_admin_gallery_path %></div></h3>
<hr>
<table class="table table-striped table-bordered"> 
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Travel</th>
    <th>操作</th>
  </tr>

<% @galleries.each do |gallery| %>
  <tr>
    <td>
      <%= gallery.id %>
    </td>
    <td><%= gallery.title %></td>
    <td><%= gallery.travel_id %></td>
    <td>
      <%= link_to '查看', [:admin, gallery] %> | 
      <%= link_to '编辑', edit_admin_gallery_path(gallery) %> | 
      <%= link_to '删除', [:admin, gallery], :confirm => '确定要删除么?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>
<%= paginate @galleries %>
</div>

app/views/admin/galleries/new.html.erb
<div class="row">
<h3>后台管理 > 创建新Gallery <div class="pull-right"><%= link_to '返回列表', admin_galleries_path %></div></h3>
<hr>
<%= render 'form' %>
</div>

app/views/admin/galleries/show.html.erb
<div class="row">
<h3>后台管理 > 画廊 / <%= @gallery.title %> <div class="pull-right"><%= link_to '编辑', edit_admin_gallery_path(@gallery) %> / <a href="/admin/galleries/<%= @gallery.id %>/photos/new">添加新图片</a></h3>
<hr>
<p id="notice"><%= notice %></p>
<table class="table table-striped table-bordered"> 
	<tr>
		<td style="width:200px;text-align:right;">ID:</td>
		<td><%= @gallery.id %></td>
	</tr>
		<tr>
		<td style="width:200px;text-align:right;">Title:</td>
		<td><%= @gallery.title %></td>
	</tr>
		<tr>
		<td style="width:200px;text-align:right;">图片:</td>
		<td>
			<% @gallery.photos.each do |photo| %>
				<img src="<%= photo.pic.url %>" alt="" style="width:200px;"><br>
				<%= photo.desc %>
				<%= link_to '编辑', edit_admin_photo_path(photo) %> | 
      	<%= link_to '删除', [:admin, photo], :confirm => '确定要删除么?', :method => :delete %>
				<br><br>
			<% end %>
		</td>
	</tr>
	</table>
</div>