config/routes.rb
Erhuamao::Application.routes.draw do
  
  get "travel_pages/index"

  resources :customizebookings

  resources :photocontests

  resources :gbookingdays

  resources :dianpins

  resources :questions

  resources :galleries

  resources :gbookings

  resources :bookings

  resources :brochure_destinations

  resources :brochure_interests

  resources :brochure_travels

  resources :brochures

  resources :pages

  resources :presses

  resources :events

  resources :photos

  resources :cities

  resources :travels do 
    resources :itineraries
    resources :datesprices
  end

  resources :destinations do
    resources :travels
  end

  resources :interests do
    resources :travels
  end

  resources :specialoffers

  resources :itineraries
  resources :datesprices

  devise_for :users
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session#, :via => Devise.mappings[:user].sign_out_via
    get 'signup' => 'devise/registrations#new', :as => :new_user_registration
    post 'signup' => 'devise/registrations#create', :as => :user_registration
    put 'signup' => 'devise/registrations#update'
    get "setting", :to => "users#setting"
    put "update_setting", :to => "users#update_setting"
    put "update_password", :to => "users#update_password"
    put "update_avatar", :to => "users#update_avatar"
    get "/users/:id", :to => "users#show", :as => :user
    get "/users/:id/dianpins", :to => "users#dianpins"
    get "/users/:id/bookings", :to => "users#bookings"
    get "/users/:id/questions", :to => "users#questions"
  end

  namespace :admin do
    resources :users do
      member do
        get :lock, :unlock, :generate_new_password_email
      end
    end
    resources :travels do 
      member do
        get :new_destination_travel
        post :create_destination_travel
        get :new_interest_travel
        post :create_interest_travel
        get :new_specialoffer_travel
        post :create_specialoffer_travel
        get :new_brochure_travel
        post :create_brochure_travel
      end
      resources :itineraries
      resources :datesprices
      resources :travel_pages do
        collection do
          put :assign
        end

        member do
          delete :detach
        end
      end
    end
    resources :datesprices
    resources :itineraries
    resources :destinations do
      resources :galleries
      member do
        get :new_brochure_destination
        post :create_brochure_destination
      end
    end
    resources :interests do
      member do
        get :new_brochure_interest
        post :create_brochure_interest
      end
    end
    resources :hotels do
      resources :galleries
    end
    resources :photos
    resources :specialoffers
    resources :presses
    resources :events
    resources :pages
    resources :banners
    resources :brochures
    resources :galleries do 
      resources :photos
    end
    resources :bookings
    resources :gbookings
    resources :questions
    resources :cities
    resources :photocontests
    resources :dianpins
    resources :shouyes
  end

  match "weibo_login" => "welcome#weibo_login"
  match "weibo_callback" => "welcome#weibo_callback"

  match "admin/travels/:id/destroy_destination_travel/:destination_id" => "admin/travels#destroy_destination_travel"
  match "admin/travels/:id/destroy_interest_travel/:interest_id" => "admin/travels#destroy_interest_travel"
  match "admin/travels/:id/destroy_specialoffer_travel/:specialoffer_id" => "admin/travels#destroy_specialoffer_travel"
  match "admin/travels/:id/destroy_brochure_travel/:brochure_id" => "admin/travels#destroy_brochure_travel"
  match "admin/interests/:id/destroy_brochure_interest/:brochure_id" => "admin/interests#destroy_brochure_interest"
  match "admin/destinations/:id/destroy_brochure_destination/:brochure_id" => "admin/destinations#destroy_brochure_destination"
  get 'admin' => 'admin/base#index'
  get 'admin/handle' => 'admin/base#handle'
  get 'search' => 'welcome#search'
  get 'travel_count' => 'welcome#travel_count'

  root :to => "welcome#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/event.rb
# -*- encoding : utf-8 -*-
class Event < ActiveRecord::Base
end

app/controllers/admin/events_controller.rb
# -*- encoding : utf-8 -*-
# insub's admin scaffold template
# rails g scaffold_controller_admin events title:string cont:text 

class Admin::EventsController < Admin::BaseController
  layout "admin"
  before_filter :authenticate_user!
  before_filter :require_admin  #, :only=> [:index], :except=> [:index]
  
  # GET /events
  # GET /events.xml
  def index
    @events = Event.order("updated_at DESC").page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(admin_events_url, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to([:admin, @event], :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(admin_events_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/events_controller.rb
# -*- encoding : utf-8 -*-
class EventsController < ApplicationController
  # GET /events
  # GET /events.xml
  def index
    @events = Event.all
    @presses = Press.all( :limit => 3)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

end

app/helpers/events_helper.rb
# -*- encoding : utf-8 -*-
module EventsHelper
end

app/views/admin/events/_form.html.erb
<%= form_for([:admin, @event],:html => {:class => "form-horizontal" }) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label">title</label>
    <div class="controls">
    <%= f.text_field :title %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">cont</label>
    <div class="controls">
    <%= f.text_area :cont %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit %>
    </div>
  </div>
<% end %>

<% content_for :footer do %>
    <script type="text/javascript" src="/plugins/u/editor_config.js"></script>
    <script type="text/javascript" src="/plugins/u/editor_all.min.js"></script>
    <link rel="stylesheet" href="/plugins/u/themes/default/css/ueditor.css" />   
    <script type="text/javascript">
      var event_cont = new UE.ui.Editor();
      new UE.ui.Editor().render('event_cont');
    </script>
<% end %>

app/views/admin/events/edit.html.erb
<div class="row">
<h3>后台管理 > 编辑event <div class="pull-right"><%= link_to '查看', [:admin, @event] %> |
<%= link_to '返回列表', admin_events_path %></div></h3>
<hr>

<%= render 'form' %>

</div>

app/views/admin/events/index.html.erb
<div class="row">
<h3>后台管理 > Event列表 <div class="pull-right"><%= link_to '创建新Events', new_admin_event_path %></div></h3>
<hr>
<table class="table table-striped table-bordered"> 
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Cont</th>
    <th>操作</th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td>
      <%= event.id %>
    </td>
    <td><%= event.title %></td>
    <td><%= raw truncate(event.cont, :length => 600, :omission => '...') %></td>
    <td>
      <%= link_to '查看', [:admin, event] %> | 
      <%= link_to '编辑', edit_admin_event_path(event) %> | 
      <%= link_to '删除', [:admin, event], :confirm => '确定要删除么?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>
<%= paginate @events %>
</div>

app/views/admin/events/new.html.erb
<div class="row">
<h3>后台管理 > 创建新Event <div class="pull-right"><%= link_to '返回列表', admin_events_path %></div></h3>
<hr>
<%= render 'form' %>
</div>

app/views/admin/events/show.html.erb
<div class="row">
<h3>后台管理 > 查看 <div class="pull-right"><%= link_to '编辑', edit_admin_event_path(@event) %> |
<%= link_to '返回列表', admin_events_path %></div></h3>
<hr>
<p id="notice"><%= notice %></p>
<table class="table table-striped table-bordered"> 
	<tr>
		<td style="width:200px;text-align:right;">ID:</td>
		<td><%= @event.id %></td>
	</tr>
		<tr>
		<td style="width:200px;text-align:right;">Title:</td>
		<td><%= @event.title %></td>
	</tr>
		<tr>
		<td style="width:200px;text-align:right;">Cont:</td>
		<td><%= raw @event.cont %></td>
	</tr>
	</table>
</div>