config/routes.rb
Erhuamao::Application.routes.draw do
  
  get "travel_pages/index"

  resources :customizebookings

  resources :photocontests

  resources :gbookingdays

  resources :dianpins

  resources :questions

  resources :galleries

  resources :gbookings

  resources :bookings

  resources :brochure_destinations

  resources :brochure_interests

  resources :brochure_travels

  resources :brochures

  resources :pages

  resources :presses

  resources :events

  resources :photos

  resources :cities

  resources :travels do 
    resources :itineraries
    resources :datesprices
  end

  resources :destinations do
    resources :travels
  end

  resources :interests do
    resources :travels
  end

  resources :specialoffers

  resources :itineraries
  resources :datesprices

  devise_for :users
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session#, :via => Devise.mappings[:user].sign_out_via
    get 'signup' => 'devise/registrations#new', :as => :new_user_registration
    post 'signup' => 'devise/registrations#create', :as => :user_registration
    put 'signup' => 'devise/registrations#update'
    get "setting", :to => "users#setting"
    put "update_setting", :to => "users#update_setting"
    put "update_password", :to => "users#update_password"
    put "update_avatar", :to => "users#update_avatar"
    get "/users/:id", :to => "users#show", :as => :user
    get "/users/:id/dianpins", :to => "users#dianpins"
    get "/users/:id/bookings", :to => "users#bookings"
    get "/users/:id/questions", :to => "users#questions"
  end

  namespace :admin do
    resources :users do
      member do
        get :lock, :unlock, :generate_new_password_email
      end
    end
    resources :travels do 
      member do
        get :new_destination_travel
        post :create_destination_travel
        get :new_interest_travel
        post :create_interest_travel
        get :new_specialoffer_travel
        post :create_specialoffer_travel
        get :new_brochure_travel
        post :create_brochure_travel
      end
      resources :itineraries
      resources :datesprices
      resources :travel_pages do
        collection do
          put :assign
        end

        member do
          delete :detach
        end
      end
    end
    resources :datesprices
    resources :itineraries
    resources :destinations do
      resources :galleries
      member do
        get :new_brochure_destination
        post :create_brochure_destination
      end
    end
    resources :interests do
      member do
        get :new_brochure_interest
        post :create_brochure_interest
      end
    end
    resources :hotels do
      resources :galleries
    end
    resources :photos
    resources :specialoffers
    resources :presses
    resources :events
    resources :pages
    resources :banners
    resources :brochures
    resources :galleries do 
      resources :photos
    end
    resources :bookings
    resources :gbookings
    resources :questions
    resources :cities
    resources :photocontests
    resources :dianpins
    resources :shouyes
  end

  match "weibo_login" => "welcome#weibo_login"
  match "weibo_callback" => "welcome#weibo_callback"

  match "admin/travels/:id/destroy_destination_travel/:destination_id" => "admin/travels#destroy_destination_travel"
  match "admin/travels/:id/destroy_interest_travel/:interest_id" => "admin/travels#destroy_interest_travel"
  match "admin/travels/:id/destroy_specialoffer_travel/:specialoffer_id" => "admin/travels#destroy_specialoffer_travel"
  match "admin/travels/:id/destroy_brochure_travel/:brochure_id" => "admin/travels#destroy_brochure_travel"
  match "admin/interests/:id/destroy_brochure_interest/:brochure_id" => "admin/interests#destroy_brochure_interest"
  match "admin/destinations/:id/destroy_brochure_destination/:brochure_id" => "admin/destinations#destroy_brochure_destination"
  get 'admin' => 'admin/base#index'
  get 'admin/handle' => 'admin/base#handle'
  get 'search' => 'welcome#search'
  get 'travel_count' => 'welcome#travel_count'

  root :to => "welcome#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/hotel.rb
# -*- encoding : utf-8 -*-
class Hotel < ActiveRecord::Base
	belongs_to :gallery
	belongs_to :destination
	belongs_to :city
	has_many :customizebookings
end

app/controllers/admin/hotels_controller.rb
# -*- encoding : utf-8 -*-
# insub's admin scaffold template
# rails g scaffold_controller_admin hotels name:string destination_id:integer 

class Admin::HotelsController < Admin::BaseController
  layout "admin"
  before_filter :authenticate_user!
  before_filter :require_admin  #, :only=> [:index], :except=> [:index]
  
  # GET /hotels
  # GET /hotels.xml
  def index
    @hotels = Hotel.order("updated_at DESC").page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @hotels }
    end
  end

  # GET /hotels/1
  # GET /hotels/1.xml
  def show
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @hotel }
    end
  end

  # GET /hotels/new
  # GET /hotels/new.xml
  def new
    @hotel = Hotel.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @hotel }
    end
  end

  # GET /hotels/1/edit
  def edit
    @hotel = Hotel.find(params[:id])
  end

  # POST /hotels
  # POST /hotels.xml
  def create
    @hotel = Hotel.new(params[:hotel])
    @hotel.gallery = Gallery.create(:title => @hotel.name)

    respond_to do |format|
      if @hotel.save
        
        format.html { redirect_to(admin_hotels_url, :notice => 'Hotel was successfully created.') }
        format.xml  { render :xml => @hotel, :status => :created, :location => @hotel }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @hotel.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /hotels/1
  # PUT /hotels/1.xml
  def update
    puts "------#{params[:hotel]}"
    @hotel = Hotel.find(params[:id])
    @hotel.gallery.update_attributes(:title => params[:hotel][:name])

    respond_to do |format|
      if @hotel.update_attributes(params[:hotel])
        format.html { redirect_to([:admin, @hotel], :notice => 'Hotel was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @hotel.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.xml
  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to(admin_hotels_url) }
      format.xml  { head :ok }
    end
  end

end


app/helpers/hotels_helper.rb
# -*- encoding : utf-8 -*-
module HotelsHelper
end

app/views/admin/hotels/_form.html.erb
<%= form_for([:admin, @hotel],:html => {:class => "form-horizontal" }) do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label">name</label>
    <div class="controls">
    <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">destination_id</label>
    <div class="controls">
    <%= f.text_field :destination_id %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/admin/hotels/edit.html.erb
<div class="row">
<h3>后台管理 > 编辑hotel <div class="pull-right"><%= link_to '查看', [:admin, @hotel] %> |
<%= link_to '返回列表', admin_hotels_path %></div></h3>
<hr>

<%= render 'form' %>

</div>

app/views/admin/hotels/index.html.erb
<div class="row">
<h3>后台管理 > Hotel列表 <div class="pull-right"><%= link_to '创建新Hotels', new_admin_hotel_path %></div></h3>
<hr>
<table class="table table-striped table-bordered"> 
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>地区</th>
    <th>城市</th>
    <th>画廊</th>
    <th>操作</th>
  </tr>

<% @hotels.each do |hotel| %>
  <tr>
    <td>
      <%= hotel.id %>
    </td>
    <td><%= hotel.name %></td>
    <td><%= hotel.destination.name if hotel.destination %></td>
    <td><%= hotel.city.name if hotel.city %></td>

    <td>
      <% if hotel.gallery %>
        <%= hotel.gallery.try(:photos).try(:size) || 0 %> / <a href="/admin/galleries/<%= hotel.gallery.id %>">管理图片</a>
    <% end %>
    </td>
    <td>
      <%= link_to '查看', [:admin, hotel] %> | 
      <%= link_to '编辑', edit_admin_hotel_path(hotel) %> | 
      <%= link_to '删除', [:admin, hotel], :confirm => '确定要删除么?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>
<%= paginate @hotels %>
</div>

app/views/admin/hotels/new.html.erb
<div class="row">
<h3>后台管理 > 创建新Hotel <div class="pull-right"><%= link_to '返回列表', admin_hotels_path %></div></h3>
<hr>
<%= render 'form' %>
</div>

app/views/admin/hotels/show.html.erb
<div class="row">
<h3>后台管理 > 查看 <div class="pull-right"><%= link_to '编辑', edit_admin_hotel_path(@hotel) %> |
<%= link_to '返回列表', admin_hotels_path %></div></h3>
<hr>
<p id="notice"><%= notice %></p>
<table class="table table-striped table-bordered"> 
	<tr>
		<td style="width:200px;text-align:right;">ID:</td>
		<td><%= @hotel.id %></td>
	</tr>
		<tr>
		<td style="width:200px;text-align:right;">Name:</td>
		<td><%= @hotel.name %></td>
	</tr>
		<tr>
		<td style="width:200px;text-align:right;">Destination:</td>
		<td><%= @hotel.destination_id %></td>
	</tr>
	</table>
</div>