config/routes.rb
Erhuamao::Application.routes.draw do
  
  get "travel_pages/index"

  resources :customizebookings

  resources :photocontests

  resources :gbookingdays

  resources :dianpins

  resources :questions

  resources :galleries

  resources :gbookings

  resources :bookings

  resources :brochure_destinations

  resources :brochure_interests

  resources :brochure_travels

  resources :brochures

  resources :pages

  resources :presses

  resources :events

  resources :photos

  resources :cities

  resources :travels do 
    resources :itineraries
    resources :datesprices
  end

  resources :destinations do
    resources :travels
  end

  resources :interests do
    resources :travels
  end

  resources :specialoffers

  resources :itineraries
  resources :datesprices

  devise_for :users
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session#, :via => Devise.mappings[:user].sign_out_via
    get 'signup' => 'devise/registrations#new', :as => :new_user_registration
    post 'signup' => 'devise/registrations#create', :as => :user_registration
    put 'signup' => 'devise/registrations#update'
    get "setting", :to => "users#setting"
    put "update_setting", :to => "users#update_setting"
    put "update_password", :to => "users#update_password"
    put "update_avatar", :to => "users#update_avatar"
    get "/users/:id", :to => "users#show", :as => :user
    get "/users/:id/dianpins", :to => "users#dianpins"
    get "/users/:id/bookings", :to => "users#bookings"
    get "/users/:id/questions", :to => "users#questions"
  end

  namespace :admin do
    resources :users do
      member do
        get :lock, :unlock, :generate_new_password_email
      end
    end
    resources :travels do 
      member do
        get :new_destination_travel
        post :create_destination_travel
        get :new_interest_travel
        post :create_interest_travel
        get :new_specialoffer_travel
        post :create_specialoffer_travel
        get :new_brochure_travel
        post :create_brochure_travel
      end
      resources :itineraries
      resources :datesprices
      resources :travel_pages do
        collection do
          put :assign
        end

        member do
          delete :detach
        end
      end
    end
    resources :datesprices
    resources :itineraries
    resources :destinations do
      resources :galleries
      member do
        get :new_brochure_destination
        post :create_brochure_destination
      end
    end
    resources :interests do
      member do
        get :new_brochure_interest
        post :create_brochure_interest
      end
    end
    resources :hotels do
      resources :galleries
    end
    resources :photos
    resources :specialoffers
    resources :presses
    resources :events
    resources :pages
    resources :banners
    resources :brochures
    resources :galleries do 
      resources :photos
    end
    resources :bookings
    resources :gbookings
    resources :questions
    resources :cities
    resources :photocontests
    resources :dianpins
    resources :shouyes
  end

  match "weibo_login" => "welcome#weibo_login"
  match "weibo_callback" => "welcome#weibo_callback"

  match "admin/travels/:id/destroy_destination_travel/:destination_id" => "admin/travels#destroy_destination_travel"
  match "admin/travels/:id/destroy_interest_travel/:interest_id" => "admin/travels#destroy_interest_travel"
  match "admin/travels/:id/destroy_specialoffer_travel/:specialoffer_id" => "admin/travels#destroy_specialoffer_travel"
  match "admin/travels/:id/destroy_brochure_travel/:brochure_id" => "admin/travels#destroy_brochure_travel"
  match "admin/interests/:id/destroy_brochure_interest/:brochure_id" => "admin/interests#destroy_brochure_interest"
  match "admin/destinations/:id/destroy_brochure_destination/:brochure_id" => "admin/destinations#destroy_brochure_destination"
  get 'admin' => 'admin/base#index'
  get 'admin/handle' => 'admin/base#handle'
  get 'search' => 'welcome#search'
  get 'travel_count' => 'welcome#travel_count'

  root :to => "welcome#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/photocontest.rb
# -*- encoding : utf-8 -*-
class Photocontest < ActiveRecord::Base
	mount_uploader :photo, PhotoUploader
end

app/controllers/admin/photocontests_controller.rb
# -*- encoding : utf-8 -*-
# insub's admin scaffold template
# rails g scaffold_controller_admin photocontests username:string name:string desc:string photo:string 

class Admin::PhotocontestsController < Admin::BaseController
  layout "admin"
  before_filter :authenticate_user!
  before_filter :require_admin  #, :only=> [:index], :except=> [:index]
  
  # GET /photocontests
  # GET /photocontests.xml
  def index
    @photocontests = Photocontest.order("updated_at DESC").page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @photocontests }
    end
  end

  # GET /photocontests/1
  # GET /photocontests/1.xml
  def show
    @photocontest = Photocontest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @photocontest }
    end
  end

  # GET /photocontests/new
  # GET /photocontests/new.xml
  def new
    @photocontest = Photocontest.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @photocontest }
    end
  end

  # GET /photocontests/1/edit
  def edit
    @photocontest = Photocontest.find(params[:id])
  end

  # POST /photocontests
  # POST /photocontests.xml
  def create
    @photocontest = Photocontest.new(params[:photocontest])

    respond_to do |format|
      if @photocontest.save
        format.html { redirect_to(admin_photocontests_url, :notice => 'Photocontest was successfully created.') }
        format.xml  { render :xml => @photocontest, :status => :created, :location => @photocontest }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @photocontest.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /photocontests/1
  # PUT /photocontests/1.xml
  def update
    @photocontest = Photocontest.find(params[:id])

    respond_to do |format|
      if @photocontest.update_attributes(params[:photocontest])
        format.html { redirect_to([:admin, @photocontest], :notice => 'Photocontest was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @photocontest.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /photocontests/1
  # DELETE /photocontests/1.xml
  def destroy
    @photocontest = Photocontest.find(params[:id])
    @photocontest.destroy

    respond_to do |format|
      format.html { redirect_to(admin_photocontests_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/photocontests_controller.rb
# -*- encoding : utf-8 -*-
class PhotocontestsController < ApplicationController
  # GET /photocontests
  # GET /photocontests.xml
  def index
    @photocontests = Photocontest.all
    @sbanner = Banner.find_by_imgname("users")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @photocontests }
    end
  end

end

app/helpers/photocontests_helper.rb
# -*- encoding : utf-8 -*-
module PhotocontestsHelper
end

app/views/admin/photocontests/_form.html.erb
<%= form_for([:admin, @photocontest],:html => {:class => "form-horizontal", :multipart => true }) do |f| %>
  <% if @photocontest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photocontest.errors.count, "error") %> prohibited this photocontest from being saved:</h2>

      <ul>
      <% @photocontest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label">username</label>
    <div class="controls">
    <%= f.text_field :username %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">name</label>
    <div class="controls">
    <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">desc</label>
    <div class="controls">
    <%= f.text_field :desc %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">photo</label>
    <div class="controls">
    <p>
      <img src="<%= @photocontest.photo.url %>">
    </p>
    <%= f.file_field :photo %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/admin/photocontests/edit.html.erb
<div class="row">
<h3>后台管理 > 编辑photocontest <div class="pull-right"><%= link_to '查看', [:admin, @photocontest] %> |
<%= link_to '返回列表', admin_photocontests_path %></div></h3>
<hr>

<%= render 'form' %>

</div>

app/views/admin/photocontests/index.html.erb
<div class="row">
<h3>后台管理 > Photocontest列表 <div class="pull-right"><%= link_to '创建新Photocontests', new_admin_photocontest_path %></div></h3>
<hr>
<table class="table table-striped table-bordered"> 
  <tr>
    <th>ID</th>
    <th>Username</th>
    <th>Name</th>
    <th>Desc</th>
    <th>Photo</th>
    <th>操作</th>
  </tr>

<% @photocontests.each do |photocontest| %>
  <tr>
    <td>
      <%= photocontest.id %>
    </td>
    <td><%= photocontest.username %></td>
    <td><%= photocontest.name %></td>
    <td><%= photocontest.desc %></td>
    <td><img src="<%= photocontest.photo.url %>" width="200"></td>
    <td>
      <%= link_to '查看', [:admin, photocontest] %> | 
      <%= link_to '编辑', edit_admin_photocontest_path(photocontest) %> | 
      <%= link_to '删除', [:admin, photocontest], :confirm => '确定要删除么?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>
<%= paginate @photocontests %>
</div>

app/views/admin/photocontests/new.html.erb
<div class="row">
<h3>后台管理 > 创建新Photocontest <div class="pull-right"><%= link_to '返回列表', admin_photocontests_path %></div></h3>
<hr>
<%= render 'form' %>
</div>

app/views/admin/photocontests/show.html.erb
<div class="row">
<h3>后台管理 > 查看 <div class="pull-right"><%= link_to '编辑', edit_admin_photocontest_path(@photocontest) %> |
<%= link_to '返回列表', admin_photocontests_path %></div></h3>
<hr>
<p id="notice"><%= notice %></p>
<table class="table table-striped table-bordered"> 
	<tr>
		<td style="width:200px;text-align:right;">ID:</td>
		<td><%= @photocontest.id %></td>
	</tr>
		<tr>
		<td style="width:200px;text-align:right;">Username:</td>
		<td><%= @photocontest.username %></td>
	</tr>
		<tr>
		<td style="width:200px;text-align:right;">Name:</td>
		<td><%= @photocontest.name %></td>
	</tr>
		<tr>
		<td style="width:200px;text-align:right;">Desc:</td>
		<td><%= @photocontest.desc %></td>
	</tr>
		<tr>
		<td style="width:200px;text-align:right;">Photo:</td>
		<td><%= @photocontest.photo %></td>
	</tr>
	</table>
</div>